# Generated by Django 2.0 on 2018-02-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180204_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtip',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
