"""
Django settings for medicapi project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b9e+jv8-6!_z!v_n-=0#o7f#mr!7%m)gm_+cik!62#75pq%fq_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition
# ADMINS = ("")
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'rest_framework_swagger',
    'django_extensions',
    'cloudinary_storage',
    'cloudinary',
    'froala_editor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medicapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ]
        },
    }
]

WSGI_APPLICATION = 'medicapi.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'
    },
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_L10N = True

USE_TZ = True

FCM_API_KEY = "AIzaSyA9_WkXOj0rQC_CVTHHr0nSjt-DcM0EwRI"
FIREBASE_API_KEY = "AIzaSyDEkbXOYi6-cR337xZvnK_VfUzDEcZySUg"
FIREBASE_AUTH_DOMAIN = "medicarch-82960.firebaseapp.com"
FIREBASE_DATABSE_URL = "https://medicarch-82960.firebaseio.com"
FIREBASE_PROJECT_ID = "medicarch-82960"
FIREBASE_STORAGE_BUCKET = "medicarch-82960.appspot.com"
FIREBASE_MESSAGING_SENDER_ID = "576787747317"


GRITS_BASE_URL = "https://grits.eha.io:443/api/v1/public_diagnose"
GRITS_API_KEY = "Cr9LPAtL"

QUICKBLOX_APP_ID = "68242"
QUICKBLOX_APP_KEY = "r-97n3knzFyJ8sn"
QUICKBLOX_APP_SECRET = "JKuvXOCUscL7j-P"

WOLFMAN_APP_ID = "WEYPX8-PEEA9EPAKH"
STOLEN_HEALTH_MAP_API_KEY = "956348929582245025 "
CLOUDINARY_URL = os.environ.get(
    "CLOUDINARY_URL",
    "cloudinary://597897783118458:IXbUW7BKVaGksM6k7Fk6IOzfdyE@hynezphri",
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
FROALA_EDITOR_PLUGINS = (
    'align',
    'char_counter',
    'code_beautifier',
    'code_view',
    'colors',
    'draggable',
    'emoticons',
    'entities',
    'file',
    'font_family',
    'font_size',
    'fullscreen',
    'image_manager',
    'image',
    'inline_style',
    'line_breaker',
    'link',
    'lists',
    'paragraph_format',
    'paragraph_style',
    'quick_insert',
    'quote',
    'save',
    'table',
    'url',
    'video',
)

STATIC_URL = '/static/'
MEDIA_URL = '/media/'  # or any prefix you choose
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
import django_heroku

django_heroku.settings(locals())
